export const agentInstructions = [
  "Large tool results use explicit bounded previews and resultRecovery; text and structured content describe the same delivered page. Read result_recover to obtain the original JSON without replay. Reserve result_recovery_prepare and pass _meta.resultRecoveryId before an effect when the whole response may be lost. Memory recovery expires/evicts and does not survive controller restart; use keyed durable jobs for crash recovery.",

  "Control the owner's Linux and Windows computers through the named device.",
  "Use devices_list/fleet_status/device_info to discover hosts, contexts, readiness and runtime capabilities.",
  "Fleet identity=auto selects a configured endpoint and reports the selected identity. An unavailable identity or timed-out probe is not evidence that the device is powered off. Use configured aliases; durable references retain the canonical device name.",
  "Use exec for a bounded purpose, fs_edit/repo_apply_patch for edits, project_run/keyed jobs for durable work and deploy_run with coordination for promotion. Group independent reads when useful; command line count is not a safety boundary.",
  "Agent capture truncation and controller preview truncation are distinct. Recovery restores only the receipt retained by the controller, never bytes the agent discarded. An expired receipt does not authorize repeating an effect.",
  "Raw exec/filesystem/PTY operations provide unrestricted native access. exec defaults to system (Linux root/Windows SYSTEM); choose identity=owner (legacy context=user) for owner credentials, repositories and user-installed programs.",
  "Prefer batch_exec/batch_read and high-level repo/project/deploy tools when they combine the required work. project_run defaults to a durable owner-context job; executable+args preserves literal argv, while command uses the native shell.",
  "Follow durable work with job_wait or job_output_since and the returned context/job ID/cursor. job_wait is capped below gateway timeouts: on waitExpired, honor retryAfterMs and repeat job_wait with the returned cursor; do not alternate rapid job_status polling. Cancelling a wait or losing its transport never cancels the job; job_cancel explicitly requests termination. Inspect terminationVerified and verification scope: Windows may return lost/partial when the root stopped but full descendant membership is unproved. Inspect exit codes, progress and partial results.",
  "Use desktop_windows then desktop_uia for Windows controls, or desktop_batch for ordered native input/screenshot actions in the interactive session.",
  "Use browser_session then browser_action for DOM/semantic locators, ordered actions, screenshots, page JavaScript and native CDP. Reuse sessionId/pageId; close sessions when finished. Attached sessions disconnect without closing the existing browser.",
  "Paged reads and logs expose continuation metadata. Follow it for full data; truncation is not completion. Timeouts/cancellation may leave completed effects, so inspect state before retrying mutations.",
  "host_power dryRun previews; scheduled confirms durable submission, not a physical transition. wake_on_lan can relay through a named agent; UDP submission is not proof of wake."
].join("\n");
